thumbor:
  image: apsl/thumbor-multiprocess:latest
  volumes:
    - ./logs:/logs
  ports:
    - "80:8000" # thumbor port
  environment:
    ALLOW_UNSAFE_URL: 'False'
    SECURITY_KEY: SECURIZE_ME
    DETECTORS: "['thumbor.detectors.feature_detector','thumbor.detectors.face_detector',]"
    AWS_ACCESS_KEY: ...
    AWS_SECRET_KEY: ...
    STORAGE: thumbor.storages.mixed_storage
    STORAGE_BUCKET: docker-thumbor-test-storage
    RESULT_STORAGE_BUCKET: docker-thumbor-test-result-storage
    UPLOAD_PHOTO_STORAGE: thumbor_aws.storages.s3_storage
    MIXED_STORAGE_FILE_STORAGE: thumbor_aws.storages.s3_storage
    RESULT_STORAGE: thumbor_aws.result_storages.s3_storage
    REDIS_STORAGE_SERVER_HOST: redis
    REDIS_STORAGE_SERVER_PORT: 6379
    REDIS_STORAGE_SERVER_DB: 0
    REDIS_QUEUE_SERVER_HOST: redis
    REDIS_QUEUE_SERVER_PORT: 6379
    REDIS_QUEUE_SERVER_DB: 0
    MIXED_STORAGE_DETECTOR_STORAGE: thumbor.storages.redis_storage
    #SENTRY_DSN_URL: # put your sentry enpoint here
    THUMBOR_NUM_PROCESSES: 16
  links:
    - redis:redis
remotecv:
  image: apsl/remotecv:latest
  links:
    - redis:redis
  environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DATABASE: 0
redis:
  image: redis:latest

