thumbor:
  image: apsl/thumbor:latest
  volumes:
    - data:/data
    - logs:/logs
  ports:
    - "8000:8000" # thumbor port
    - "8001:80" # nginx port (cache)
  environment:
    DETECTORS: ['thumbor.detectors.face_detector','thumbor.detectors.feature_detector',]
