version: '2'
services:
  thumbor:
    image: apsl/thumbor:latest
    volumes:
      - tmp:/data
    environment:
      - ALLOW_UNSAFE_URL=True # False if you are in prod
      - SECURITY_KEY=SECURIZE_ME # Change it
      - DETECTORS=["thumbor.detectors.queued_detector.queued_complete_detector"]
      - RESULT_STORAGE=thumbor.result_storages.file_storage
      - REDIS_STORAGE_SERVER_HOST=redis
      - REDIS_STORAGE_SERVER_PORT=6379
      - REDIS_STORAGE_SERVER_DB=0
      - REDIS_QUEUE_SERVER_HOST=redis
      - REDIS_QUEUE_SERVER_PORT=6379
      - REDIS_QUEUE_SERVER_DB=0
      - MIXED_STORAGE_DETECTOR_STORAGE=thumbor.storages.redis_storage
    networks:
      - app
  nginx:
    image: apsl/thumbor-nginx:latest
    links:
      - thumbor:thumbor
    volumes_from:
      - thumbor
    ports:
      - "80:80"
    networks:
      - app
  redis:
    image: redis:latest
    networks:
      - app
  remotecv:
    image: apsl/remotecv:latest
    links:
      - redis:redis
    environment:
      - REMOTECV_REDIS_HOST=redis
      - REMOTECV_REDIS_PORT=6379
      - REMOTECV_REDIS_DATABASE=0
    networks:
      - app
volumes:
  tmp:
    driver: local
networks:
  app:
    driver: bridge
