# Usage (to create or update):
# 
# gcloud init
# gcloud auth login
# gcloud components install kubectl
# gcloud container clusters get-credentials [cluster-name] --project [Project ID]
## (http://kubernetes.io/docs/user-guide/managing-deployments/#kubectl-apply)
# kubectl apply -f .
#
#
#
# inspired from
# https://github.com/kubernetes/kubernetes/blob/d4251b2a259ad3b185e13e218b13634d627e0274/examples/guestbook/all-in-one/guestbook-all-in-one.yaml
apiVersion: v1
kind: Service
metadata:
  name: thumbor-service
  labels:
    app: thumbor
    tier: backend
    role: master
spec:
  ports:
    # the port that this service should serve on
  - port: 28765
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: thumbor
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thumbor-deployment
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: redis
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: thumbor
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: apsl/thumbor:6.3.0
        # envvars
        env:
        -
          name: MAX_WIDTH
          value: "2048"
        -
          name: MAX_HEIGHT
          value: "2048"
        -
          name: MAX_SOURCE_SIZE
          value: "10485760"
        -
          name: STORAGE_EXPIRATION_SECONDS
          value: "0"
        -
          name: DETECTORS
          value: "['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']"
        -
          name: USE_GIFSICLE_ENGINE
          value: "True"
        -
          name: HTTP_LOADER_CONNECT_TIMEOUT
          value: "1"
        -
          name: HTTP_LOADER_REQUEST_TIMEOUT
          value: "5"
        -
          name: HTTP_LOADER_PROXY_HOST
          value: "'10.132.0.8'"
        -
          name: HTTP_LOADER_PROXY_PORT
          value: "8888"
        -
          name: HTTP_LOADER_FOLLOW_REDIRECTS
          value: "False"
          
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
          # limits:
          #   memory: 500Mi
        livenessProbe:
          # an http probe
          httpGet:
            path: /unsafe/1000x1000/smart/https%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Fpingdom-test%2Ftest-image.png
            port: 8000
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 30
          timeoutSeconds: 1
        ports:
        - containerPort: 8000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: thumbor-hpa
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: thumbor-deployment
  minReplicas: 10
  maxReplicas: 200
  targetCPUUtilizationPercentage: 50
