# Usage (to create or update):
# 
# gcloud init
# gcloud auth login
# gcloud components install kubectl
# gcloud container clusters get-credentials [cluster-name] --project [Project ID]
## (http://kubernetes.io/docs/user-guide/managing-deployments/#kubectl-apply)
# kubectl apply -f .
#
#
#
# inspired from
# https://github.com/kubernetes/kubernetes/blob/d4251b2a259ad3b185e13e218b13634d627e0274/examples/guestbook/all-in-one/guestbook-all-in-one.yaml
apiVersion: v1
kind: Service
metadata:
  name: thumbor-service
  labels:
    app: thumbor
    tier: backend
    role: master
spec:
  ports:
    # the port that this service should serve on
  - port: 28765
    targetPort: 8000
  type: LoadBalancer
  selector:
    app: thumbor
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: thumbor-deployment
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: redis
  #   role: master
  #   tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     role: master
  #     tier: backend
  template:
    metadata:
      labels:
        app: thumbor
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: smarp/thumbor:1.0.2
        # envvars
        env:
        - name: MAX_WIDTH
          value: 2048
        env:
        - name: MAX_HEIGHT
          value: 2048
        env:
        - name: MAX_SOURCE_SIZE
          value: 10485760
        env:
        - name: STORAGE_EXPIRATION_SECONDS
          value: 0
        env:
        - name: DETECTORS
          value: [\'thumbor.detectors.feature_detector\',\'thumbor.detectors.face_detector\']
        env:
        - name: USE_GIFSICLE_ENGINE
          value: True
        env:
        - name: HTTP_LOADER_CONNECT_TIMEOUT
          value: 1
                
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: thumbor-hpa
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: thumbor-deployment
  minReplicas: 4
  maxReplicas: 50
  targetCPUUtilizationPercentage: 80
