thumbor:
  image: apsl/thumbor:latest
  volumes:
    - data:/data
  ports:
    - "80:8000" # thumbor port
  environment:
    DETECTORS: ['thumbor.detectors.face_detector','thumbor.detectors.feature_detector',]
